module.exports = function(grunt) {

    // Configuration goes here
    grunt.initConfig({
    
        //pkg: grunt.file.readJSON("package.json"),
        
        clean: {
            build: ["app/js/all_body.min.js","app/css/all_app.min.css"]
        },
        
        // Lint the Javascript, exclude the vendor folder
        jshint: {
            all: [
                "Gruntfile.js",
                "app/js/**.js",
                "!app/js/all_body.min.js",
                "!app/js/vendor/**.js"
            ],
            options: {
                curly: true,
                eqeqeq: true,
                immed: true,
                latedef: true,
                newcap: true,
                noarg: true,
                sub: true,
                undef: true,
                boss: true,
                eqnull: true,
                browser: true,
                globals: {
                    window: false,
                    console: false,
                    document: false,
                    setTimeout: false,
                    
                    // Grunt globals
                    module: false,
                    
                    // Vendor globals may not be redefined
                    jQuery: false,
                    $: false
                }
            }
        },
        
        // Combine and compress JS
        // Just put files that needs to go in head there manually. 
        // Put files that can go in the bottom of body here.
        uglify: {
            options: {
                mangle: false,
                compress: false,
                beautify: true
            },
            body_js: {
                files: {
                    "app/js/all_body.min.js": [
                        "app/js/vendor/bootstrap.min.js",
                        "app/js/vendor/holder.js",
                        "app/js/config.js",
                        "app/js/main.js"
                    ]
                }
            }
        },
       
        
        
        
        // Compress CSS
        cssmin: {
            combine: {
              files: {
                'app/css/all_app.min.css': ['app/css/bootstrap-3.0.3.css','app/css/main.css', 'app/css/navbar.css']
              }
            }
        },
        
        watch: {
            css: {
                files: [
                    "app/css/*.css",
                    "!app/css/all_app.min.css"
                ],
                tasks: ["cssmin"],
                options: {
                    livereload: true
                }
            },
            js: {
                files: [
                    "Gruntfile.js",
                    "app/js/**.js",
                    "!app/js/vendor/**.js",
                    "!app/js/all_body.min.js"
                ],
                tasks: ["uglify"],
                options: {
                    livereload: true
                }
            },
            other: {
                files: [
                    "app/index.html",
                    "app/media/*",
                    "app/media/images/*",
                    "app/media/images/carousel/*"
                ],
                options: {
                    livereload: true
                }
            }
        }
    });

    // Load plugins here
    grunt.loadNpmTasks("grunt-contrib-clean");
    grunt.loadNpmTasks("grunt-contrib-jshint");
    grunt.loadNpmTasks('grunt-contrib-uglify');
    
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    
    grunt.loadNpmTasks("grunt-contrib-watch");

    // TASKS
    
    // Use this during development
    grunt.registerTask("default", ["clean:build", "uglify", "cssmin"]);
    
    // Use this when deploying
    grunt.registerTask("build", ["default"]);

    // Use this to jshint all files
    // grunt jshint
    
    // Use this to delete all autogenerated files
    // grunt clean
    
    
};